### ISSUE TITLE
pip install -r requirements.txt throws error

### ISSUE THREAD

**Issue by pankajkgupta** [int-brain-lab/paper-behavior#2]
Hi, I installed iblenv as per the instructions, activate it and tried to install the requirements on this repo using 
`pip install -r requirements.txt`
but that throws an error as shown in the image below
![image](https://user-images.githubusercontent.com/1904197/95294801-ca437800-082a-11eb-81c7-b768906349e8.png)

**Comment by k1o0** [comment]
Sorry that was a typo.  For now you can delete the `ibl-pipeline-light` line from the requirements.txt file.  You don't actually need it if you're using iblenv, but we're trying to remove iblenv as a dependency.

**Comment by pankajkgupta** [comment]
Thanks! that worked.
